// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzqnccsmejplilhmisgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6cW5jY3NtZWpwbGlsaG1pc2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjA4MzEsImV4cCI6MjA2MDAzNjgzMX0.ou3o4WiB7NDmU7Mj0kiwXYuf1OjFK_WxmwBGy2d_Dhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);